
AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable
  SuggestExtensions: false

  Include:
    - 'config.ru'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'

  Exclude:
    - 'bin/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'app/views/**/*'

Layout/IndentationConsistency:
  EnforcedStyle: 'indented_internal_methods'

Layout/LineLength:
  Max: 80
  Exclude:
    - 'config/environments/*'
    - 'config/initializers/*'

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
    - 'config/environments/*'

Metrics/ClassLength:
  Exclude:
    - 'db/seeds.rb'
  Max: 150

Metrics/ModuleLength:
  Max: 150

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes